In [1]:
# Name: Soham Samanta | Roll : 20051107 | CSE-21 | T&T Lab Sessional
# I. Convert a vector of ints into a matrix binary representation.
# II.  Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [2]:
# I.
import numpy as np

def int_to_binary_matrix(vector):
    max_bin_len = len(bin(max(vector))[2:])
    binary_matrix = []

    for num in vector:
        binary_repr = bin(num)[2:].zfill(max_bin_len)
        binary_matrix.append([int(digit) for digit in binary_repr])

    return np.array(binary_matrix)

vector = np.array([1, 2, 3, 4, 5])
binary_matrix = int_to_binary_matrix(vector)
print("Binary Matrix:")
print(binary_matrix)


Binary Matrix:
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


In [3]:
# II.
import numpy as np

# Create the 5x2 integer array
array = np.arange(100, 200, 10).reshape(5, 2)

print("5x2 Integer Array:")
print(array)


5x2 Integer Array:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
