In [2]:
# SOHAM SAMANTA | 20051107 | TT-Lab4 
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

1.22.3


In [6]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
import numpy as np
x=np.array(42)
a=np.array([1,2,3,4])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


print(x.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])

3


In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


In [23]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element on 2nd row: ',arr[1,3])

4th element on 2nd row:  9


In [24]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [28]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [29]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [30]:
import numpy as np
arr=np.array([[1,2,3],[4,5,7]])
print(arr[1,-1])

7


In [31]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[4,5,7,9,11,12]])
print(arr[1,1::2])

[ 5  9 12]


In [32]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[4,5,7,9,11,12]])
print(arr[0:2,2])

[3 7]


In [33]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[4,5,7,9,11,12]])
print(arr[0:2,1:4])

[[2 3 4]
 [5 7 9]]


In [34]:
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [35]:
import numpy as np
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [36]:
import numpy as np
arr=np.array([1,2,3],dtype='S')
print(arr.dtype)

|S1


In [37]:
import numpy as np
arr=np.array([1,2,3])
x=arr.copy()
arr[0]=43

print(arr)
print(x)

[43  2  3]
[1 2 3]


In [38]:
arr=np.array([1,2,3])
x=arr.view()
arr[0]=43

print(arr)
print(x)

[43  2  3]
[43  2  3]


In [39]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [40]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [42]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [43]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3, 4, 5]]), array([[4, 5, 6, 7, 8]]), array([], shape=(0, 5), dtype=int64)]
